vich_uploader:
    db_driver: orm

    mappings:
       galery_picture:
           uri_prefix: /galery_pictures
           upload_destination: '%kernel.project_dir%/public/galery_pictures'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

       paragraph_image:
           uri_prefix: /paragraph_images
           upload_destination: '%kernel.project_dir%/public/paragraph_images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

       sponsor:
           uri_prefix: /sponsor_images
           upload_destination: '%kernel.project_dir%/public/sponsor_images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
