<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVpU7mYe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVpU7mYe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVpU7mYe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVpU7mYe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVpU7mYe\App_KernelDevDebugContainer([
    'container.build_hash' => 'VpU7mYe',
    'container.build_id' => '32cf4a8e',
    'container.build_time' => 1636375518,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVpU7mYe');
